[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
rand = "0.8.5"
image = "0.24.5"
cgmath = "0.18.0"
measurements = "0.11.0"
queues = "1.1.0"